### PR TITLE
Release 1.2.4

### PR DESCRIPTION
**Pull request by NicoHood**
#8 fix.
@PaulRB Please test on your x4, x5 and also the 328 again.
If it works, I will merge it.

```
1.2.4 Release (21.03.2016)
* Fixed Attinyx4/x5 Issue #8
```

### CODE REVIEW

**Comment by PaulRB** [comment]
Now my newbie status with GitHub is my problem! What is the best way for me to download 1.2.4?

**Comment by NicoHood** [comment]
`git clone https://github.com/NicoHood/PinChangeInterrupt.git`

Or for micro$$$$: https://github.com/NicoHood/PinChangeInterrupt/tree/dev

**Comment by PaulRB** [comment]
OK, thanks. Testing on tiny84 now.
PC Int on pins 0, 2, 3, 4, 5, 6, 7 works!
PC Int on pins 1, 8, 9, 10 does not work. I verified my wiring is correct in the same way as before.

Partial success. Should I go on to test '85 and Nano or wait for you to fix?

**Comment by PaulRB** [comment]
Now testing on Nano 3:
PC Int on pins 8, 9, 10, 11, 12, 13 works!
PC Int on pins 2, 3, 4, 5, 6, 7, A0, A1, A2, A3, A4, A5 does not work. They did before (at least some of them)
A port related problem?

**Comment by NicoHood** [comment]
Please redownload. Thx for testing.
Now please also test for 85 and 328 please. That'd be super nice.

**Comment by PaulRB** [comment]
No improvement, on '84 or Nano. How can I be sure I have your latest changes? I deleted PinChangeInterrupt folder from sketchbook/libraries and re-downloaded Zip from your link above to replace it, and re-started IDE.

**Comment by NicoHood** [comment]
Pin5 works on my nano. Restart the IDE and redownload the lib.

**Comment by PaulRB** [comment]
Please accept my apologies, I can't explain my earlier results with nano. Works OK now for any pin.

Re-testing the '84, it is still working on some pins and not others, like before.

I will re-test '85 later, maybe tomorrow. I have run out of breadboards and must dissasemble the '84 circuit to make the '85 circuit.

I guess you do not have an '84 for testing?

Thanks again for your work on this!

**Comment by NicoHood** [comment]
I do not have a 84. Its weird that it does not work like this.
If you still have problems report which pins work and which not. (and the pin layout please, i need port numbers, not pin labels)

**Comment by PaulRB** [comment]
ATtiny84:
```
Ard Pin    Port Pin    PCInt    Status
0          PA0         PCINT0   Working
1          PA1         PCINT1   Not working
2          PA2         PCINT2   Working
3          PA3         PCINT3   Working
4          PA4         PCINT4   Working
5          PA5         PCINT5   Working
6          PA6         PCINT6   Working
7          PA7         PCINT7   Working
8          PB2         PCINT10  Not working
9          PB1         PCINT9   Not working
10        PB0         PCINT8   Not working

```

**Comment by NicoHood** [comment]
That is weird. Are you sure that the 328 works on all pins? Also PCINT1 should work. I see no reason why it should not.

I will do some compilation tests later when i am home again.

**Comment by PaulRB** [comment]
Nano 3 (ATmegs328):
Arduino pins 2,3,4,5,6,7,8,9,10,11,12,13,A0,A1,A2,A3,A4,A5 Working
Only pins not working:
- 0,1.  These are TX & RX, so I'm not sure they would work with PC Ints
- A6,A7. I seem to remember these are analog only, can't be used as digital input

**Comment by NicoHood** [comment]
I manually disabled portb on attiny x4:
https://github.com/NicoHood/PinChangeInterrupt/blob/master/src/PinChangeInterruptSettings.h#L217

Or dont you use an crystal on the attiny? What do you think? should i enable those pins?

However If we keep it disabled I neet to add an asterisk here:
https://github.com/NicoHood/PinChangeInterrupt#pinchangeinterrupt-table

Pin1 should work though. Are you sure it is not connected to any other hardware?

**Comment by PaulRB** [comment]
ATtiny85:
All pins 0,1,2,3,4 working for PC ints

ATtiny84:
I have only ever used internal oscillator.
Nothing else attached to pin 1. Remember my breadboard photos from https://github.com/NicoHood/PinChangeInterrupt/issues/8 ?

**Comment by NicoHood** [comment]
This output shows, that something compiles wrong:
https://github.com/NicoHood/PinChangeInterrupt/issues/8#issuecomment-199256025

I will try to fix pin1 and suggest to keep portB disabled, as it shrinks the code size a lot more.

**Comment by NicoHood** [comment]
This was the error: https://github.com/NicoHood/PinChangeInterrupt/commit/d3b05998c938a0b2261bec2bb0363662e39dc5e5

However I am still wondering why port1 did not work. also your ouput clearly shows that it should have compiled before. Now it is clear that it does not work, as I have deactivated it. I will try again later.

Now all portA pins should work as expected. PortB I have to take a look at, however it will stay deactivated in the default settings.

**Comment by NicoHood** [comment]
Please try this branch and check if all x4 pins work (the one on Port1 aka PB, not port0):
https://github.com/NicoHood/PinChangeInterrupt/tree/allx4

And also try this and report port1 (PB):
https://github.com/NicoHood/PinChangeInterrupt/tree/e0c2a2d0d4b9deaac8d145d63bc6c46101d37711

**Comment by PaulRB** [comment]
@NicoHood, the allx4 version has corrected pc int on arduino pin 1! Congratulations! However, pc int is still not working on arduino pins 8, 9, 10 (=PB). I am not sure what you meant by "all x4 pins". There are only 3 pins on port PB, unless you include the reset pin. I do not know how to change the reset pin to be an input pin, and I am concerned that if I try, I could brick my '84.

With the second link, pc ints do not work on arduino pins 8, 9, 10 either. Also Arduino pin 1 does not work on this version.

**Comment by NicoHood** [comment]
Okay the allx4 pins branch should work with all 84 pins (especially focussed on 8,9, 10). I will try to find the issue, and let you know. And yes, disabling reset bricks your device in most of the cases, nevermind that.

There are different sleep modes. Some of them work with the interrupts, some not. The best way to look this up is the datasheet. However I never tried this. Here is one example: http://playground.arduino.cc/Learning/ArduinoSleepCode

**Comment by NicoHood** [comment]
For now it takes me too much time to find the bug without hardware. I'd need to get an attiny 84 sample or someone else needs to debug it. However this SHOULD be debugged, as there might be other issues.

The last thing you can do is to add the following at the beginning of setup():
```cpp
PCMSK1  |= 0xff; // enable all 4 PORTB pins (normally we only use 1)
GIMSK |= (1<<PCIE1); // enable PORTB PCINT
```

This SHOULD work. If it does not, replace all "1" with "0" and check the PORTA again.

Otherwise there must go something wrong with the attaching of the function pointer.

**Comment by NicoHood** [comment]
You still here?

**Comment by PaulRB** [comment]
Hi Nico, sorry, busy with personal stuff, will get around to doing those tests soon.

**Comment by PaulRB** [comment]
@NicoHood, that did the trick! Pin interrupts now working on Arduino pins 8, 9 & 10.

```
#include "PinChangeInterrupt.h"

#define BUTTON  10
#define LED 1

void setup() {
  
  PCMSK1  |= 0xff; // enable all 4 PORTB pins (normally we only use 1)
  GIMSK |= (1 << PCIE1); // enable PORTB PCINT
  
  pinMode(BUTTON, INPUT_PULLUP);
  pinMode(LED, OUTPUT);
  attachPCINT(digitalPinToPCINT(BUTTON), buttonInterrupt, CHANGE);

}

void buttonInterrupt() {
  digitalWrite(LED, digitalRead(BUTTON));
}


void loop() {
  //digitalWrite(LED, digitalRead(BUTTON));
}
```

> If it does not, replace all "1" with "0" and check the PORTA again.

Did not understand what you meant by that. Hopefully this does not matter

**Comment by NicoHood** [comment]
Now try to comment `PCMSK1...` and try again.
Then comment `GIMSK...` instead and try.

It seems one of those two are not set properly by the Library.
Thx for the feedback!

**Comment by PaulRB** [comment]
This line is needed:

`  PCMSK1  |= 0xff; // enable all 4 PORTB pins (normally we only use 1)
`
This line is not needed, pc interrupts still work with it commented out:

 ` //GIMSK |= (1 << PCIE1); // enable PORTB PCINT`

**Comment by NicoHood** [comment]
Finally!
https://github.com/NicoHood/PinChangeInterrupt/tree/allx4

Now try to use the library as usual with all attiny 84 pins again. It should finally all work.
This is the patch, if you are interested:
https://github.com/NicoHood/PinChangeInterrupt/commit/8ef075dfcb32bea08e8c89238686c61dc7a0983d

The problem is (if you look at the datahsheet) those 2 registers are normally next to each other while they are not for attiny.

Even if it works, the new version 1.2.4 will still have them disabled by default. This is because it safes a lot of flash and those 4 pins can be used for better functions normally. You can activate them in the Settings.h though.

**Comment by PaulRB** [comment]
OK. I deleted my PinChangeInterrupt folder from libraries and downloaded the zip from your link above, extracted the contents to libraries and renamed the folder from "PinChangeInterrupt-allx4" to "PinChangeInterrupt". Then I restarted the IDE and loaded this code:
```

#include "PinChangeInterrupt.h"

#define BUTTON  0
#define LED 1

void setup() {
  
  //PCMSK1  |= 0xff; // enable all 4 PORTB pins (normally we only use 1)
  //GIMSK |= (1 << PCIE1); // enable PORTB PCINT
  
  pinMode(BUTTON, INPUT_PULLUP);
  pinMode(LED, OUTPUT);
  attachPCINT(digitalPinToPCINT(BUTTON), buttonInterrupt, CHANGE);

}

void buttonInterrupt() {
  digitalWrite(LED, digitalRead(BUTTON));
}


void loop() {
  //digitalWrite(LED, digitalRead(BUTTON));
}
```
Pin change interrupts work on Arduino pins 0 to 7 but don't work on 8, 9, 10. To make it work with 8, 9, 10, I still have to insert the line

`  PCMSK1  |= 0xff; // enable all 4 PORTB pins (normally we only use 1)`


Did you intend that I should edit Settings.h in the new download?

**Comment by NicoHood** [comment]
Nah, just download and try again. Nothing to modify. I tried to fix it again.

**Comment by PaulRB** [comment]
Well done Nick. PC ints now working on all '84 pins without having to set PCMSK1 or GIMSK. (RESET not tested, as discussed before. Thanks for your work fixing this!

Should I close the issue now, or will you do that?

**Comment by NicoHood** [comment]
I will merge the commits, prepare a release and finally close the issue.

Thanks for all the help!

**Pull request merged**
